# Configuration for autoupdating dependencies daily.
#
# Once a day, at midnight UTC, we check for updates to
# - ICU
# - ccache for Windows
# - Python for Windows
# - Python for Mac OS X
# - Python for macOS universal
# - Cython
#
# For each dependency that has an update, we create a pull request containing a
# single commit that updates the dependency.

name: Dependency Autoupdate Daily

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      BUILD_PULL_REQUEST:
        type: boolean
        description: Build pull requests created by this workflow
        default: true

jobs:
  autoupdate-ICU:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v3
      - name: search for update
        run: $GITHUB_WORKSPACE/actions/update_icu.py ${{ secrets.GITHUB_TOKEN }}
      - name: allow building pull requests
        id: allow
        if: github.event_name == 'schedule' || github.event.inputs.BUILD_PULL_REQUEST == 'true'
        run: echo "ACTIONS_TOKEN=${{ secrets.ACTIONS_TOKEN }}" >> $GITHUB_ENV
      - name: prevent building pull requests
        if: github.event_name != 'schedule' && github.event.inputs.BUILD_PULL_REQUEST == 'false'
        run: echo "ACTIONS_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - name: apply update
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          assignees: isc-adang
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit-message: "[autoupdate-ICU] update ICU from \"${{ env.ICU_NAME_OLD }}\" to \"${{ env.ICU_NAME_LATEST }}\""
          branch: autoupdate-ICU
          delete-branch: true
          token: ${{ env.ACTIONS_TOKEN }}
          title: "[autoupdate] Update ICU from \"${{ env.ICU_NAME_OLD }}\" to \"${{ env.ICU_NAME_LATEST }}\""
          body: |-
            As of ${{ env.ICU_PUBLISHED_AT }}, a new version of ICU has been released.

            Release Information (sourced from ${{ env.ICU_HTML_URL }})
            <blockquote>

            ${{ env.ICU_RELEASE_INFO }}
            </blockquote>

            *I am a bot, and this action was performed automatically.*
      - name: enable automerge
        if: steps.allow.outcome == 'success' && steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ env.ACTIONS_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: rebase

  autoupdate-JSON:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v3
      - name: search for update
        run: $GITHUB_WORKSPACE/actions/update_json.py ${{ secrets.GITHUB_TOKEN }}
      - name: allow building pull requests
        id: allow
        if: github.event_name == 'schedule' || github.event.inputs.BUILD_PULL_REQUEST == 'true'
        run: echo "ACTIONS_TOKEN=${{ secrets.ACTIONS_TOKEN }}" >> $GITHUB_ENV
      - name: prevent building pull requests
        if: github.event_name != 'schedule' && github.event.inputs.BUILD_PULL_REQUEST == 'false'
        run: echo "ACTIONS_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - name: apply update
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          assignees: isc-adang
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit-message: "[autoupdate-JSON] update JSON for Modern C++ from \"${{ env.JSON_VERSION_OLD }}\" to \"${{ env.JSON_VERSION_LATEST }}\""
          branch: autoupdate-JSON
          delete-branch: true
          token: ${{ env.ACTIONS_TOKEN }}
          title: "[autoupdate] Update JSON for Modern C++ from \"${{ env.JSON_VERSION_OLD }}\" to \"${{ env.JSON_VERSION_LATEST }}\""
          body: |-
            As of ${{ env.JSON_PUBLISHED_AT }}, a new version of JSON for Modern C++ has been released.

            Release Information (sourced from ${{ env.JSON_HTML_URL }})
            <blockquote>

            ${{ env.JSON_RELEASE_INFO }}
            </blockquote>

            *I am a bot, and this action was performed automatically.*
      - name: enable automerge
        if: steps.allow.outcome == 'success' && steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ env.ACTIONS_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: rebase

  autoupdate-ccache:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v3
      - name: install Python packages
        run: pip3 install --user beautifulsoup4
      - name: search for update
        run: $GITHUB_WORKSPACE/actions/update_ccache.py ${{ secrets.GITHUB_TOKEN }}
      - name: allow building pull requests
        id: allow
        if: github.event_name == 'schedule' || github.event.inputs.BUILD_PULL_REQUEST == 'true'
        run: echo "ACTIONS_TOKEN=${{ secrets.ACTIONS_TOKEN }}" >> $GITHUB_ENV
      - name: prevent building pull requests
        if: github.event_name != 'schedule' && github.event.inputs.BUILD_PULL_REQUEST == 'false'
        run: echo "ACTIONS_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - name: apply update
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          assignees: isc-adang
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit-message: "[autoupdate-ccache] update ccache from ${{ env.CCACHE_VERSION_OLD }} to ${{ env.CCACHE_VERSION }}"
          branch: autoupdate-ccache
          delete-branch: true
          token: ${{ env.ACTIONS_TOKEN }}
          title: "[autoupdate] Update ccache from ${{ env.CCACHE_VERSION_OLD }} to ${{ env.CCACHE_VERSION }}"
          body: |-
            As of ${{ env.CCACHE_PUBLISHED_AT }}, a new version of ccache for Windows has been released.

            Changelog (sourced from ${{ env.CCACHE_CHANGELOG_URL }})
            <blockquote>

            ${{ env.CCACHE_CHANGELOG }}
            </blockquote>

            *I am a bot, and this action was performed automatically.*
      - name: enable automerge
        if: steps.allow.outcome == 'success' && steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ env.ACTIONS_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: rebase

  autoupdate-cython:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v3
      - name: install Python packages
        run: pip3 install --user requests beautifulsoup4
      - name: search for update
        run: $GITHUB_WORKSPACE/actions/update_cython.py
      - name: allow building pull requests
        id: allow
        if: github.event_name == 'schedule' || github.event.inputs.BUILD_PULL_REQUEST == 'true'
        run: echo "ACTIONS_TOKEN=${{ secrets.ACTIONS_TOKEN }}" >> $GITHUB_ENV
      - name: prevent building pull requests
        if: github.event_name != 'schedule' && github.event.inputs.BUILD_PULL_REQUEST == 'false'
        run: echo "ACTIONS_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - name: apply update
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          assignees: isc-adang
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit-message: "[autoupdate-cython] update Cython from ${{ env.CYTHON_VERSION_OLD }} to ${{ env.CYTHON_VERSION_LATEST }}"
          branch: autoupdate-cython
          delete-branch: true
          token: ${{ env.ACTIONS_TOKEN }}
          title: "[autoupdate] Update Cython from ${{ env.CYTHON_VERSION_OLD }} to ${{ env.CYTHON_VERSION_LATEST }}"
          body: |-
            A new version of Cython is available.

            Changelog (sourced from https://cython.readthedocs.io/en/stable/src/changes.html)
            <blockquote>

            ${{ env.CYTHON_CHANGELOG }}
            </blockquote>

            *I am a bot, and this action was performed automatically.*
      - name: enable automerge
        if: steps.allow.outcome == 'success' && steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ env.ACTIONS_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: rebase

  autoupdate-python-windows:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v3
      - name: search for update
        run: $GITHUB_WORKSPACE/actions/update_python.py win64
      - name: allow building pull requests
        id: allow
        if: github.event_name == 'schedule' || github.event.inputs.BUILD_PULL_REQUEST == 'true'
        run: echo "ACTIONS_TOKEN=${{ secrets.ACTIONS_TOKEN }}" >> $GITHUB_ENV
      - name: prevent building pull requests
        if: github.event_name != 'schedule' && github.event.inputs.BUILD_PULL_REQUEST == 'false'
        run: echo "ACTIONS_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - name: apply update
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          assignees: isc-adang
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit-message: "[autoupdate-python-windows] update Python for Windows: ${{ env.PYTHON_UPDATE_INFO_ONELINE }}"
          branch: autoupdate-python-windows
          delete-branch: true
          token: ${{ env.ACTIONS_TOKEN }}
          title: "[autoupdate] Update Python for Windows: ${{ env.PYTHON_UPDATE_INFO_ONELINE }}"
          body: |-
            A new version of Python for Windows is available.

            ${{ env.PYTHON_UPDATE_INFO_MULTILINE }}

            For details of all Python releases, see https://www.nuget.org/packages/python.

            *I am a bot, and this action was performed automatically.*
      - name: enable automerge
        if: steps.allow.outcome == 'success' && steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ env.ACTIONS_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: rebase

  autoupdate-python-osx:
    runs-on: macos-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v3
      - name: search for update
        run: $GITHUB_WORKSPACE/actions/update_python.py osx
      - name: allow building pull requests
        id: allow
        if: github.event_name == 'schedule' || github.event.inputs.BUILD_PULL_REQUEST == 'true'
        run: echo "ACTIONS_TOKEN=${{ secrets.ACTIONS_TOKEN }}" >> $GITHUB_ENV
      - name: prevent building pull requests
        if: github.event_name != 'schedule' && github.event.inputs.BUILD_PULL_REQUEST == 'false'
        run: echo "ACTIONS_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - name: apply update
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          assignees: isc-adang
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit-message: "[autoupdate-python-osx] update Python for Mac OS X: ${{ env.PYTHON_UPDATE_INFO_ONELINE }}"
          branch: autoupdate-python-osx
          delete-branch: true
          token: ${{ env.ACTIONS_TOKEN }}
          title: "[autoupdate] Update Python for Mac OS X: ${{ env.PYTHON_UPDATE_INFO_ONELINE }}"
          body: |-
            A new version of Python for Mac OS X is available.

            ${{ env.PYTHON_UPDATE_INFO_MULTILINE }}

            For details of the updated versions, see https://github.com/pyenv/pyenv/releases/v${{ env.PYENV_TOOL_VERSION }}.

            *I am a bot, and this action was performed automatically.*
      - name: enable automerge
        if: steps.allow.outcome == 'success' && steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ env.ACTIONS_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: rebase

  autoupdate-python-macosuniversal:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v3
      - name: search for update
        run: |
          pip3 install beautifulsoup4
          $GITHUB_WORKSPACE/actions/update_python.py macos
      - name: allow building pull requests
        id: allow
        if: github.event_name == 'schedule' || github.event.inputs.BUILD_PULL_REQUEST == 'true'
        run: echo "ACTIONS_TOKEN=${{ secrets.ACTIONS_TOKEN }}" >> $GITHUB_ENV
      - name: prevent building pull requests
        if: github.event_name != 'schedule' && github.event.inputs.BUILD_PULL_REQUEST == 'false'
        run: echo "ACTIONS_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - name: apply update
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          assignees: isc-adang
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit-message: "[autoupdate-python-macosuniversal] update Python for macOS universal: ${{ env.PYTHON_UPDATE_INFO_ONELINE }}"
          branch: autoupdate-python-macosuniversal
          delete-branch: true
          token: ${{ env.ACTIONS_TOKEN }}
          title: "[autoupdate] Update Python for macOS universal: ${{ env.PYTHON_UPDATE_INFO_ONELINE }}"
          body: |-
            A new version of Python for macOS universal is available.

            ${{ env.PYTHON_UPDATE_INFO_MULTILINE }}

            For details of all Python releases, see https://www.python.org/downloads/macos/.

            *I am a bot, and this action was performed automatically.*
      - name: enable automerge
        if: steps.allow.outcome == 'success' && steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ env.ACTIONS_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: rebase
